// Code generated by hertz generator.

package user

import (
	"universe/utils"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return utils.JwtAuth("/v1/users/sms_code", "/v1/users/login", "/v1/users/refresh_token")
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendsmscodeMw() []app.HandlerFunc {
	// Token bucket removed as it's now provided by the SDK
	return nil
}

func _users0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
