// Code generated by hertz generator.

package ledger

import (
	"universe/utils"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return utils.JwtAuth()
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ledgerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _entriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createledgerentryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listledgerentriesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteledgerentryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateledgerentryMw() []app.HandlerFunc {
	// your code...
	return nil
}
