// Code generated by hertz generator.

package main

import (
	"context"
	"os"
	"strconv"
	"universe/gdb"
	"universe/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	cors "github.com/hertz-contrib/cors"
	"github.com/joho/godotenv"
	"golang.org/x/time/rate"
)

// @title Hertz API 文档
// @version 1.0
// @description 基于 Hertz 框架的 Swagger 文档示例
// @host https://www.miemie.tech
// @BasePath /universe
func main() {
	ctx := context.Background()

	_ = godotenv.Load("/etc/universe/.env")

	// Initialize logger (default to INFO if LOG_LEVEL is not set)
	logLevel := os.Getenv("LOG_LEVEL")
	if logLevel == "" {
		logLevel = "info"
	}
	utils.InitLogger(logLevel)

	if os.Getenv("SKIP_GDB_INIT") != "1" {
		gdb.MustInit()
		defer gdb.Dispose(ctx)
	}

	h := server.Default(server.WithHostPorts(":12000"))
	h.Use(cors.New(cors.Config{
		AllowOriginFunc: func(origin string) bool {
			return origin == "capacitor://localhost"
		},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowHeaders:     []string{"Authorization", "Content-Type", "Accept", "Origin", "X-Requested-With"},
		AllowCredentials: true,
		ExposeHeaders:    []string{"Content-Length", "Content-Type"},
		MaxAge:           600,
	}))
	rpsStr := os.Getenv("RATE_LIMIT_RPS")
	burstStr := os.Getenv("RATE_LIMIT_BURST")
	var rps float64 = 100
	var burst int = 200
	if rpsStr != "" {
		if v, err := strconv.ParseFloat(rpsStr, 64); err == nil && v > 0 {
			rps = v
		}
	}
	if burstStr != "" {
		if v, err := strconv.Atoi(burstStr); err == nil && v > 0 {
			burst = v
		}
	}
	limiter := rate.NewLimiter(rate.Limit(rps), burst)

	h.Use(func(ctx context.Context, c *app.RequestContext) {
		if !limiter.Allow() {
			utils.Logger.Warn("rate limit exceeded")
			c.String(consts.StatusTooManyRequests, "Too Many Requests")
			c.Abort()
			return
		}
		c.Next(ctx)
	})

	// Add global middleware to log all incoming API calls
	h.Use(func(ctx context.Context, c *app.RequestContext) {
		// Log the incoming request details
		utils.Logger.Infof("Incoming request: Method=%s, Path=%s, Host=%s",
			c.Request.Header.Method(),
			c.Request.URI().PathOriginal(),
			c.Request.Host())

		// Continue to the next handler
		c.Next(ctx)
	})

	register(h)
	h.Spin()
}
