// Code generated by hertz generator.

package main

import (
	handler "universe/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/dbcheck", handler.DbCheck)

	r.GET("/schema", handler.SchemaList)
	r.GET("/schema/:filename", handler.SchemaDownload)
	r.GET("/xstar/update/*filepath", handler.XstarUpdate)
	r.GET("/xstar/manifest", handler.XstarManifest)
}
